chore(dependencies): Upgrade Spring Boot to 2.3.12 auto-bump spring framework to 5.2.15 and fasterxml jackson-bom to 2.11.4 While building kork with upgrade, faced errors like:
Task :kork-core:compileJava
/kork/kork-core/src/main/java/com/netflix/spinnaker/kork/lock/LockManager.java:19: error: package com.fasterxml.jackson.annotation does not exist
import com.fasterxml.jackson.annotation.JsonCreator;
                                       ^
/kork/kork-core/src/main/java/com/netflix/spinnaker/kork/lock/LockManager.java:20: error: package com.fasterxml.jackson.annotation does not exist
import com.fasterxml.jackson.annotation.JsonInclude;
                                       ^
/kork/kork-core/src/main/java/com/netflix/spinnaker/kork/lock/LockManager.java:21: error: package com.fasterxml.jackson.annotation does not exist
import com.fasterxml.jackson.annotation.JsonProperty;
                                       ^
To resolve errors, introduced explicit implementation of com.fasterxml.jackson.core:jackson-annotations and com.fasterxml.jackson.core:jackson-databind in kork-core.gradle.

And com.fasterxml.jackson.core:jackson-databind in kork-jedis.gradle